### ISSUE TITLE
Indicate status of the repo in README

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-tools#1]
It is currently not clear what the status of the tools in this repo are. E.g., are these ready for production use, what tools are available etc. 

It would be useful to add a description of the intended use and level of support for the tools in this repo to the README.

**Comment by rly** [comment]
Done. I added "These tools are NOT ready for production use. There is no guarantee of support for these tools."

After I add tests and CI, I will update this notice.
